// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Btjo1XmM8TU5hR_YqJjZ5F1oYXWRZ0I',
    appId: '1:633441857207:web:6090a0958cc191ac742732',
    messagingSenderId: '633441857207',
    projectId: 'workonit-68ac9',
    authDomain: 'workonit-68ac9.firebaseapp.com',
    storageBucket: 'workonit-68ac9.appspot.com',
    measurementId: 'G-QHZSCRTLL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlHcwwiOfXh0gGqt5oO4GRSqd9NqFh3tA',
    appId: '1:633441857207:android:53254ee9676dbf9b742732',
    messagingSenderId: '633441857207',
    projectId: 'workonit-68ac9',
    storageBucket: 'workonit-68ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqHvslQkY4GQ8QFF7CIoUrImZbf3fD7m0',
    appId: '1:633441857207:ios:d5a86cdc31efc39b742732',
    messagingSenderId: '633441857207',
    projectId: 'workonit-68ac9',
    storageBucket: 'workonit-68ac9.appspot.com',
    iosBundleId: 'com.example.thaiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqHvslQkY4GQ8QFF7CIoUrImZbf3fD7m0',
    appId: '1:633441857207:ios:daa984eb964bc1de742732',
    messagingSenderId: '633441857207',
    projectId: 'workonit-68ac9',
    storageBucket: 'workonit-68ac9.appspot.com',
    iosBundleId: 'com.example.thaiapp.RunnerTests',
  );
}
